from __future__ import annotations

import unittest

import zhiyun_light_control as zlight
from zhiyun_light_control import (
    LightBridgeClient,
    LightConnectionConfig,
    LightController,
    LightIntegration,
    LightRig,
    LightSetupProfile,
    Scene,
    load_light_connection_config,
    load_light_setup_profile,
    save_light_connection_config,
    save_light_setup_profile,
)
from zhiyun_light_control.protocol import RuntimeCommand, first_frame
from zhiyun_light_control.transports.ble import BleProfile

STABLE_PUBLIC_API = (
    "AsyncLightController",
    "AsyncLightIntegration",
    "AsyncLightRig",
    "AsyncProbeResult",
    "AsyncZhiyunLight",
    "CommandResult",
    "CueError",
    "CueLibrary",
    "IntegrationNotReady",
    "LightBridgeClient",
    "LightBridgeError",
    "LightBridgeNotReady",
    "LightBridgeUnconfirmed",
    "LightConnectionConfig",
    "LightController",
    "LightFixture",
    "LightIntegration",
    "LightProject",
    "LightProjectError",
    "LightRig",
    "LightSetupProfile",
    "LightStatusReport",
    "MeshConfigAccessMessagePlan",
    "MeshNetworkPlan",
    "MeshProxyPdu",
    "PersistentLightFactory",
    "PresetError",
    "ProbeResult",
    "ProvisioningCapabilities",
    "ProvisioningDataPlan",
    "ProvisioningFailure",
    "ProvisioningPublicKey",
    "ProvisioningSessionSecrets",
    "ProvisionerKeypair",
    "RigConfigError",
    "RigNotReady",
    "RuntimeCommandSpec",
    "RuntimeFrameSpec",
    "Scene",
    "SceneCommandPlan",
    "ScenePresetLibrary",
    "SceneState",
    "SceneStateTracker",
    "SceneTransition",
    "SerializedPlanBundle",
    "SetupProfileMissing",
    "SetupProfileNotReady",
    "UnconfirmedCommandError",
    "ZhiyunLight",
    "aes_ccm_encrypt",
    "aes_cmac",
    "async_iter_state_events",
    "async_rig_from_json",
    "async_rig_from_mapping",
    "build_config_app_key_add_params",
    "build_mesh_config_sequence_plan",
    "build_mesh_proxy_pdu",
    "build_provisioning_data_plan",
    "build_provisioner_confirmation",
    "build_provisioner_random",
    "build_provisioning_data",
    "build_provisioning_invite",
    "build_provisioning_public_key",
    "build_provisioning_start",
    "build_provisioning_start_no_oob",
    "build_zy_mesh_network_plan",
    "close_async_light_factory",
    "command_results_acknowledged",
    "confirmation_inputs",
    "cue_from_mapping",
    "derive_shared_ecdh_secret",
    "generate_network_key",
    "execute_async_command_plan",
    "execute_async_command_plan_confirmed",
    "execute_async_frame_plan",
    "execute_async_frame_plan_confirmed",
    "execute_async_serialized_frame_plan",
    "execute_async_serialized_frame_plan_confirmed",
    "execute_async_transition_frame_plans",
    "execute_async_transition_frame_plans_confirmed",
    "execute_async_transition_plans",
    "execute_async_transition_plans_confirmed",
    "execute_command_plan",
    "execute_command_plan_confirmed",
    "execute_frame_plan",
    "execute_frame_plan_confirmed",
    "execute_serialized_frame_plan",
    "execute_serialized_frame_plan_confirmed",
    "execute_transition_frame_plans",
    "execute_transition_frame_plans_confirmed",
    "execute_transition_plans",
    "execute_transition_plans_confirmed",
    "fixture_from_mapping",
    "generate_application_key",
    "generate_provisioning_random",
    "generate_provisioner_keypair",
    "integration_pending_action_ids",
    "integration_ready",
    "integration_ready_for",
    "integration_require",
    "integration_warnings",
    "interpolate_scene",
    "iter_state_events",
    "light_connection_config_from_json",
    "light_connection_config_from_mapping",
    "light_connection_config_to_json",
    "light_project_from_mapping",
    "light_project_to_json",
    "light_setup_profile_from_json",
    "light_setup_profile_from_mapping",
    "light_setup_profile_to_json",
    "load_async_rig",
    "load_light_connection_config",
    "load_light_project",
    "load_light_setup_profile",
    "load_rig",
    "load_rig_mapping",
    "load_serialized_plan_bundle",
    "make_light_factory",
    "merge_scene",
    "mesh_k1",
    "mesh_salt",
    "open_async_light",
    "open_light",
    "pack_mesh_key_indexes",
    "parse_mesh_proxy_pdu",
    "parse_provisioning_confirmation",
    "parse_provisioning_capabilities",
    "parse_provisioning_failure",
    "parse_provisioning_public_key",
    "parse_provisioning_random",
    "provisioning_data_plaintext",
    "provisioning_session_secrets",
    "read_async_status",
    "read_sync_status",
    "require_command_result",
    "require_command_results",
    "rig_from_json",
    "rig_from_mapping",
    "rig_profile_bundle_mapping",
    "rig_setup_profiles_from_report",
    "rig_to_json",
    "save_light_connection_config",
    "save_light_project",
    "save_light_setup_profile",
    "save_rig",
    "save_rig_profile_bundle",
    "save_serialized_plan_bundle",
    "scene_command_plan",
    "scene_command_specs",
    "scene_frame_specs",
    "scene_from_mapping",
    "scene_transition",
    "serialized_frame_commands",
    "serialized_plan_bundle",
    "serialized_plan_bundle_from_json",
    "serialized_plan_bundle_to_json",
    "serialized_plan_payload",
    "setup_profile_capabilities",
    "setup_profile_primitive_readiness",
    "setup_profile_primitive_readiness_map",
    "setup_profile_primitive_ready",
    "setup_profile_primitive_ready_for",
    "setup_profile_primitive_requirements",
    "setup_profile_primitive_requirements_map",
    "setup_profile_ready",
    "setup_profile_summary",
    "setup_profile_unready_capabilities",
    "setup_profile_unready_primitive_capabilities",
    "state_event_payload",
    "state_history_payload",
    "transition_command_plans",
    "verify_provisionee_confirmation",
)


class PublicApiTests(unittest.TestCase):
    def test_root_all_is_curated_sdk_surface(self) -> None:
        self.assertEqual(tuple(zlight.__all__), STABLE_PUBLIC_API)

    def test_documented_example_imports_remain_root_exports(self) -> None:
        exports = {
            LightBridgeClient,
            LightConnectionConfig,
            LightController,
            LightIntegration,
            LightRig,
            LightSetupProfile,
            Scene,
            load_light_connection_config,
            load_light_setup_profile,
            save_light_connection_config,
            save_light_setup_profile,
        }
        self.assertEqual(len(exports), 11)
        for name in (
            "LightBridgeClient",
            "LightConnectionConfig",
            "LightController",
            "LightIntegration",
            "LightRig",
            "LightSetupProfile",
            "Scene",
            "load_light_connection_config",
            "load_light_setup_profile",
            "save_light_connection_config",
            "save_light_setup_profile",
        ):
            self.assertIn(name, zlight.__all__)

    def test_low_level_symbols_live_in_modules_not_public_root_all(self) -> None:
        self.assertNotIn("RuntimeCommand", zlight.__all__)
        self.assertNotIn("first_frame", zlight.__all__)
        self.assertNotIn("BleProfile", zlight.__all__)

        self.assertIs(zlight.RuntimeCommand, RuntimeCommand)
        self.assertIs(zlight.first_frame, first_frame)
        self.assertIs(zlight.BleProfile, BleProfile)


if __name__ == "__main__":
    unittest.main()
